# SPDX-License-Identifier: Apache-2.0

FROM quay.io/fedora/fedora-minimal AS builder

# Packaged dependencies
RUN microdnf install -y \
    cargo \
    dnf-plugins-core \
    git \
    make \
    openssl-devel \
    rust

# build
RUN git clone https://github.com/toshisasaki/deduplicator /src/deduplicator
WORKDIR /src/deduplicator
RUN ls -la && cargo build --release

FROM quay.io/fedora/fedora-minimal:latest

RUN microdnf makecache && \
    microdnf -y install openssl-devel rust-openssl-devel

# now assemble a release docker image using a fedora minimal base image
FROM quay.io/fedora/fedora-minimal
ARG VERSION=latest
LABEL org.opencontainers.image.authors="Anderson Toshiyuki Sasaki <11450334+toshisasaki@users.noreply.github.com>"
LABEL org.opencontainers.image.version="$VERSION"
LABEL org.opencontainers.image.title="Deduplicator"
LABEL org.opencontainers.image.description="Deduplicate files"
LABEL org.opencontainers.image.url="https://github.com/toshisasaki/deduplicator"
LABEL org.opencontainers.image.source="https://github.com/toshisasaki/deduplicator"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.vendor="Anderson Toshiyuki Sasaki"

# these labels are set in the fedora base image and should be overwritten
LABEL name="Deduplicator"
LABEL version="$VERSION"
LABEL license="Apache-2.0"
LABEL vendor="Anderson Toshiyuki Sasaki"

# Install runtime dependencies
RUN microdnf makecache && \
    microdnf -y install openssl && \
    microdnf clean all && \
    rm -rf /var/cache/dnf/*

# now copy the deduplicator from the builder
COPY --from=builder /src/deduplicator/target/release/deduplicator /bin/deduplicator
